2022-06-22 13:11:28,993 INFO: News Aggregator [in C:\Users\ranganath\Desktop\001 Profession\news aggregator\app\__init__.py:33]
2022-06-22 13:21:47,889 ERROR: Exception on / [GET] [in C:\Users\ranganath\Desktop\001 Profession\news aggregator\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "C:\Users\ranganath\Desktop\001 Profession\news aggregator\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\ranganath\Desktop\001 Profession\news aggregator\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\ranganath\Desktop\001 Profession\news aggregator\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ranganath\Desktop\001 Profession\news aggregator\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\ranganath\Desktop\001 Profession\news aggregator\app\routes.py", line 11, in index
    return render_template('index.html', news=news)
  File "C:\Users\ranganath\Desktop\001 Profession\news aggregator\venv\lib\site-packages\flask\templating.py", line 148, in render_template
    return _render(
  File "C:\Users\ranganath\Desktop\001 Profession\news aggregator\venv\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "C:\Users\ranganath\Desktop\001 Profession\news aggregator\venv\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\ranganath\Desktop\001 Profession\news aggregator\venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\ranganath\Desktop\001 Profession\news aggregator\app\templates\index.html", line 21, in top-level template code
    <li><a href="{{ url_for('news', category='India') }}">India</a></li>
  File "C:\Users\ranganath\Desktop\001 Profession\news aggregator\venv\lib\site-packages\flask\helpers.py", line 336, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Users\ranganath\Desktop\001 Profession\news aggregator\venv\lib\site-packages\flask\helpers.py", line 323, in url_for
    rv = url_adapter.build(
  File "C:\Users\ranganath\Desktop\001 Profession\news aggregator\venv\lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'news' with values ['category']. Did you mean 'index' instead?
2022-06-22 13:23:35,333 ERROR: Exception on / [GET] [in C:\Users\ranganath\Desktop\001 Profession\news aggregator\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "C:\Users\ranganath\Desktop\001 Profession\news aggregator\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\ranganath\Desktop\001 Profession\news aggregator\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\ranganath\Desktop\001 Profession\news aggregator\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ranganath\Desktop\001 Profession\news aggregator\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\ranganath\Desktop\001 Profession\news aggregator\app\routes.py", line 11, in index
    return render_template('index.html', news=news)
  File "C:\Users\ranganath\Desktop\001 Profession\news aggregator\venv\lib\site-packages\flask\templating.py", line 148, in render_template
    return _render(
  File "C:\Users\ranganath\Desktop\001 Profession\news aggregator\venv\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "C:\Users\ranganath\Desktop\001 Profession\news aggregator\venv\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\ranganath\Desktop\001 Profession\news aggregator\venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\ranganath\Desktop\001 Profession\news aggregator\app\templates\index.html", line 21, in top-level template code
    <li><a href="{{ url_for('news', category='India') }}">India</a></li>
  File "C:\Users\ranganath\Desktop\001 Profession\news aggregator\venv\lib\site-packages\flask\helpers.py", line 336, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Users\ranganath\Desktop\001 Profession\news aggregator\venv\lib\site-packages\flask\helpers.py", line 323, in url_for
    rv = url_adapter.build(
  File "C:\Users\ranganath\Desktop\001 Profession\news aggregator\venv\lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'news' with values ['category']. Did you mean 'index' instead?
2022-06-22 13:24:27,509 INFO: News Aggregator [in C:\Users\ranganath\Desktop\001 Profession\news aggregator\app\__init__.py:33]
2022-06-22 13:24:57,954 ERROR: Exception on /news/India [GET] [in C:\Users\ranganath\Desktop\001 Profession\news aggregator\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "C:\Users\ranganath\Desktop\001 Profession\news aggregator\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\ranganath\Desktop\001 Profession\news aggregator\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\ranganath\Desktop\001 Profession\news aggregator\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ranganath\Desktop\001 Profession\news aggregator\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\ranganath\Desktop\001 Profession\news aggregator\app\routes.py", line 18, in news
    return render_template('news.html', news=n)
  File "C:\Users\ranganath\Desktop\001 Profession\news aggregator\venv\lib\site-packages\flask\templating.py", line 149, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Users\ranganath\Desktop\001 Profession\news aggregator\venv\lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\ranganath\Desktop\001 Profession\news aggregator\venv\lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "C:\Users\ranganath\Desktop\001 Profession\news aggregator\venv\lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\ranganath\Desktop\001 Profession\news aggregator\venv\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\ranganath\Desktop\001 Profession\news aggregator\venv\lib\site-packages\flask\templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\ranganath\Desktop\001 Profession\news aggregator\venv\lib\site-packages\flask\templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: news.html
